server:
  port: 8888
spring:
  application:
    name: server

dubbo:
  application:
    name: ${spring.application.name}
  protocols:
    # 多协议端口不能相同
    grpc:
      name: grpc
      port: 20881
    dubbo:
      name: dubbo
      port: 20880
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181