// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_message.proto

package com.guagua.proto.bookstore;

public final class BookMessage {
  private BookMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookstore_Book_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookstore_Book_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022book_message.proto\022\tbookstore\032\024author_" +
      "message.proto\"m\n\004Book\022\n\n\002id\030\001 \001(\r\022\014\n\004nam" +
      "e\030\002 \001(\t\022\025\n\rselling_price\030\003 \001(\001\022\021\n\tpublis" +
      "her\030\004 \001(\t\022!\n\006author\030\005 \001(\0132\021.bookstore.Au" +
      "thorB\036\n\032com.guagua.proto.bookstoreP\001b\006pr" +
      "oto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.guagua.proto.bookstore.AuthorMessage.getDescriptor(),
        }, assigner);
    internal_static_bookstore_Book_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bookstore_Book_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookstore_Book_descriptor,
        new java.lang.String[] { "Id", "Name", "SellingPrice", "Publisher", "Author", });
    com.guagua.proto.bookstore.AuthorMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
