// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_message.proto

package com.guagua.proto.bookstore;

public interface BookOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookstore.Book)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <pre>
   * 书名
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <pre>
   * 书名
   * </pre>
   *
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <pre>
   * 售价
   * </pre>
   *
   * <code>double selling_price = 2;</code>
   */
  double getSellingPrice();

  /**
   * <pre>
   * 出版公司
   * </pre>
   *
   * <code>string publisher = 3;</code>
   */
  java.lang.String getPublisher();
  /**
   * <pre>
   * 出版公司
   * </pre>
   *
   * <code>string publisher = 3;</code>
   */
  com.google.protobuf.ByteString
      getPublisherBytes();

  /**
   * <pre>
   * 作者
   * </pre>
   *
   * <code>.bookstore.Author author = 4;</code>
   */
  boolean hasAuthor();
  /**
   * <pre>
   * 作者
   * </pre>
   *
   * <code>.bookstore.Author author = 4;</code>
   */
  com.guagua.proto.bookstore.AuthorMessage.Author getAuthor();
  /**
   * <pre>
   * 作者
   * </pre>
   *
   * <code>.bookstore.Author author = 4;</code>
   */
  com.guagua.proto.bookstore.AuthorMessage.AuthorOrBuilder getAuthorOrBuilder();
}
