// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_service.proto

package com.guagua.proto.bookstore;

public final class BookServiceOuterClass {
  private BookServiceOuterClass() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookstore_CreateBookRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookstore_CreateBookRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookstore_CreateBookResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookstore_CreateBookResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022book_service.proto\022\tbookstore\032\022book_me" +
      "ssage.proto\"2\n\021CreateBookRequest\022\035\n\004book" +
      "\030\001 \001(\0132\017.bookstore.Book\"3\n\022CreateBookRes" +
      "ponse\022\035\n\004book\030\001 \001(\0132\017.bookstore.Book2U\n\013" +
      "BookService\022F\n\007addBook\022\034.bookstore.Creat" +
      "eBookRequest\032\035.bookstore.CreateBookRespo" +
      "nseB\036\n\032com.guagua.proto.bookstoreP\001b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.guagua.proto.bookstore.BookMessage.getDescriptor(),
        }, assigner);
    internal_static_bookstore_CreateBookRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bookstore_CreateBookRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookstore_CreateBookRequest_descriptor,
        new java.lang.String[] { "Book", });
    internal_static_bookstore_CreateBookResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_bookstore_CreateBookResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookstore_CreateBookResponse_descriptor,
        new java.lang.String[] { "Book", });
    com.guagua.proto.bookstore.BookMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
