// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_store_message.proto

package com.guagua.proto.bookstore;

public final class BookStoreMessage {
  private BookStoreMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface BookStoreOrBuilder extends
      // @@protoc_insertion_point(interface_extends:bookstore.BookStore)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>repeated .bookstore.Book book = 2;</code>
     */
    java.util.List<com.guagua.proto.bookstore.Book> 
        getBookList();
    /**
     * <code>repeated .bookstore.Book book = 2;</code>
     */
    com.guagua.proto.bookstore.Book getBook(int index);
    /**
     * <code>repeated .bookstore.Book book = 2;</code>
     */
    int getBookCount();
    /**
     * <code>repeated .bookstore.Book book = 2;</code>
     */
    java.util.List<? extends com.guagua.proto.bookstore.BookOrBuilder> 
        getBookOrBuilderList();
    /**
     * <code>repeated .bookstore.Book book = 2;</code>
     */
    com.guagua.proto.bookstore.BookOrBuilder getBookOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code bookstore.BookStore}
   */
  public  static final class BookStore extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:bookstore.BookStore)
      BookStoreOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BookStore.newBuilder() to construct.
    private BookStore(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BookStore() {
      name_ = "";
      book_ = java.util.Collections.emptyList();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BookStore(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              if (!((mutable_bitField0_ & 0x00000002) != 0)) {
                book_ = new java.util.ArrayList<com.guagua.proto.bookstore.Book>();
                mutable_bitField0_ |= 0x00000002;
              }
              book_.add(
                  input.readMessage(com.guagua.proto.bookstore.Book.parser(), extensionRegistry));
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000002) != 0)) {
          book_ = java.util.Collections.unmodifiableList(book_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guagua.proto.bookstore.BookStoreMessage.internal_static_bookstore_BookStore_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guagua.proto.bookstore.BookStoreMessage.internal_static_bookstore_BookStore_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guagua.proto.bookstore.BookStoreMessage.BookStore.class, com.guagua.proto.bookstore.BookStoreMessage.BookStore.Builder.class);
    }

    private int bitField0_;
    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BOOK_FIELD_NUMBER = 2;
    private java.util.List<com.guagua.proto.bookstore.Book> book_;
    /**
     * <code>repeated .bookstore.Book book = 2;</code>
     */
    public java.util.List<com.guagua.proto.bookstore.Book> getBookList() {
      return book_;
    }
    /**
     * <code>repeated .bookstore.Book book = 2;</code>
     */
    public java.util.List<? extends com.guagua.proto.bookstore.BookOrBuilder> 
        getBookOrBuilderList() {
      return book_;
    }
    /**
     * <code>repeated .bookstore.Book book = 2;</code>
     */
    public int getBookCount() {
      return book_.size();
    }
    /**
     * <code>repeated .bookstore.Book book = 2;</code>
     */
    public com.guagua.proto.bookstore.Book getBook(int index) {
      return book_.get(index);
    }
    /**
     * <code>repeated .bookstore.Book book = 2;</code>
     */
    public com.guagua.proto.bookstore.BookOrBuilder getBookOrBuilder(
        int index) {
      return book_.get(index);
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      for (int i = 0; i < book_.size(); i++) {
        output.writeMessage(2, book_.get(i));
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      for (int i = 0; i < book_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, book_.get(i));
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.guagua.proto.bookstore.BookStoreMessage.BookStore)) {
        return super.equals(obj);
      }
      com.guagua.proto.bookstore.BookStoreMessage.BookStore other = (com.guagua.proto.bookstore.BookStoreMessage.BookStore) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getBookList()
          .equals(other.getBookList())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      if (getBookCount() > 0) {
        hash = (37 * hash) + BOOK_FIELD_NUMBER;
        hash = (53 * hash) + getBookList().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.guagua.proto.bookstore.BookStoreMessage.BookStore prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code bookstore.BookStore}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:bookstore.BookStore)
        com.guagua.proto.bookstore.BookStoreMessage.BookStoreOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.guagua.proto.bookstore.BookStoreMessage.internal_static_bookstore_BookStore_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.guagua.proto.bookstore.BookStoreMessage.internal_static_bookstore_BookStore_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.guagua.proto.bookstore.BookStoreMessage.BookStore.class, com.guagua.proto.bookstore.BookStoreMessage.BookStore.Builder.class);
      }

      // Construct using com.guagua.proto.bookstore.BookStoreMessage.BookStore.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
          getBookFieldBuilder();
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        if (bookBuilder_ == null) {
          book_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
        } else {
          bookBuilder_.clear();
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.guagua.proto.bookstore.BookStoreMessage.internal_static_bookstore_BookStore_descriptor;
      }

      @java.lang.Override
      public com.guagua.proto.bookstore.BookStoreMessage.BookStore getDefaultInstanceForType() {
        return com.guagua.proto.bookstore.BookStoreMessage.BookStore.getDefaultInstance();
      }

      @java.lang.Override
      public com.guagua.proto.bookstore.BookStoreMessage.BookStore build() {
        com.guagua.proto.bookstore.BookStoreMessage.BookStore result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.guagua.proto.bookstore.BookStoreMessage.BookStore buildPartial() {
        com.guagua.proto.bookstore.BookStoreMessage.BookStore result = new com.guagua.proto.bookstore.BookStoreMessage.BookStore(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        result.name_ = name_;
        if (bookBuilder_ == null) {
          if (((bitField0_ & 0x00000002) != 0)) {
            book_ = java.util.Collections.unmodifiableList(book_);
            bitField0_ = (bitField0_ & ~0x00000002);
          }
          result.book_ = book_;
        } else {
          result.book_ = bookBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.guagua.proto.bookstore.BookStoreMessage.BookStore) {
          return mergeFrom((com.guagua.proto.bookstore.BookStoreMessage.BookStore)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.guagua.proto.bookstore.BookStoreMessage.BookStore other) {
        if (other == com.guagua.proto.bookstore.BookStoreMessage.BookStore.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (bookBuilder_ == null) {
          if (!other.book_.isEmpty()) {
            if (book_.isEmpty()) {
              book_ = other.book_;
              bitField0_ = (bitField0_ & ~0x00000002);
            } else {
              ensureBookIsMutable();
              book_.addAll(other.book_);
            }
            onChanged();
          }
        } else {
          if (!other.book_.isEmpty()) {
            if (bookBuilder_.isEmpty()) {
              bookBuilder_.dispose();
              bookBuilder_ = null;
              book_ = other.book_;
              bitField0_ = (bitField0_ & ~0x00000002);
              bookBuilder_ = 
                com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                   getBookFieldBuilder() : null;
            } else {
              bookBuilder_.addAllMessages(other.book_);
            }
          }
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.guagua.proto.bookstore.BookStoreMessage.BookStore parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.guagua.proto.bookstore.BookStoreMessage.BookStore) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.util.List<com.guagua.proto.bookstore.Book> book_ =
        java.util.Collections.emptyList();
      private void ensureBookIsMutable() {
        if (!((bitField0_ & 0x00000002) != 0)) {
          book_ = new java.util.ArrayList<com.guagua.proto.bookstore.Book>(book_);
          bitField0_ |= 0x00000002;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.guagua.proto.bookstore.Book, com.guagua.proto.bookstore.Book.Builder, com.guagua.proto.bookstore.BookOrBuilder> bookBuilder_;

      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public java.util.List<com.guagua.proto.bookstore.Book> getBookList() {
        if (bookBuilder_ == null) {
          return java.util.Collections.unmodifiableList(book_);
        } else {
          return bookBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public int getBookCount() {
        if (bookBuilder_ == null) {
          return book_.size();
        } else {
          return bookBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public com.guagua.proto.bookstore.Book getBook(int index) {
        if (bookBuilder_ == null) {
          return book_.get(index);
        } else {
          return bookBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public Builder setBook(
          int index, com.guagua.proto.bookstore.Book value) {
        if (bookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBookIsMutable();
          book_.set(index, value);
          onChanged();
        } else {
          bookBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public Builder setBook(
          int index, com.guagua.proto.bookstore.Book.Builder builderForValue) {
        if (bookBuilder_ == null) {
          ensureBookIsMutable();
          book_.set(index, builderForValue.build());
          onChanged();
        } else {
          bookBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public Builder addBook(com.guagua.proto.bookstore.Book value) {
        if (bookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBookIsMutable();
          book_.add(value);
          onChanged();
        } else {
          bookBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public Builder addBook(
          int index, com.guagua.proto.bookstore.Book value) {
        if (bookBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureBookIsMutable();
          book_.add(index, value);
          onChanged();
        } else {
          bookBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public Builder addBook(
          com.guagua.proto.bookstore.Book.Builder builderForValue) {
        if (bookBuilder_ == null) {
          ensureBookIsMutable();
          book_.add(builderForValue.build());
          onChanged();
        } else {
          bookBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public Builder addBook(
          int index, com.guagua.proto.bookstore.Book.Builder builderForValue) {
        if (bookBuilder_ == null) {
          ensureBookIsMutable();
          book_.add(index, builderForValue.build());
          onChanged();
        } else {
          bookBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public Builder addAllBook(
          java.lang.Iterable<? extends com.guagua.proto.bookstore.Book> values) {
        if (bookBuilder_ == null) {
          ensureBookIsMutable();
          com.google.protobuf.AbstractMessageLite.Builder.addAll(
              values, book_);
          onChanged();
        } else {
          bookBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public Builder clearBook() {
        if (bookBuilder_ == null) {
          book_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000002);
          onChanged();
        } else {
          bookBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public Builder removeBook(int index) {
        if (bookBuilder_ == null) {
          ensureBookIsMutable();
          book_.remove(index);
          onChanged();
        } else {
          bookBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public com.guagua.proto.bookstore.Book.Builder getBookBuilder(
          int index) {
        return getBookFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public com.guagua.proto.bookstore.BookOrBuilder getBookOrBuilder(
          int index) {
        if (bookBuilder_ == null) {
          return book_.get(index);  } else {
          return bookBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public java.util.List<? extends com.guagua.proto.bookstore.BookOrBuilder> 
           getBookOrBuilderList() {
        if (bookBuilder_ != null) {
          return bookBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(book_);
        }
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public com.guagua.proto.bookstore.Book.Builder addBookBuilder() {
        return getBookFieldBuilder().addBuilder(
            com.guagua.proto.bookstore.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public com.guagua.proto.bookstore.Book.Builder addBookBuilder(
          int index) {
        return getBookFieldBuilder().addBuilder(
            index, com.guagua.proto.bookstore.Book.getDefaultInstance());
      }
      /**
       * <code>repeated .bookstore.Book book = 2;</code>
       */
      public java.util.List<com.guagua.proto.bookstore.Book.Builder> 
           getBookBuilderList() {
        return getBookFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilderV3<
          com.guagua.proto.bookstore.Book, com.guagua.proto.bookstore.Book.Builder, com.guagua.proto.bookstore.BookOrBuilder> 
          getBookFieldBuilder() {
        if (bookBuilder_ == null) {
          bookBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
              com.guagua.proto.bookstore.Book, com.guagua.proto.bookstore.Book.Builder, com.guagua.proto.bookstore.BookOrBuilder>(
                  book_,
                  ((bitField0_ & 0x00000002) != 0),
                  getParentForChildren(),
                  isClean());
          book_ = null;
        }
        return bookBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:bookstore.BookStore)
    }

    // @@protoc_insertion_point(class_scope:bookstore.BookStore)
    private static final com.guagua.proto.bookstore.BookStoreMessage.BookStore DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.guagua.proto.bookstore.BookStoreMessage.BookStore();
    }

    public static com.guagua.proto.bookstore.BookStoreMessage.BookStore getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BookStore>
        PARSER = new com.google.protobuf.AbstractParser<BookStore>() {
      @java.lang.Override
      public BookStore parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BookStore(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BookStore> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BookStore> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.guagua.proto.bookstore.BookStoreMessage.BookStore getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_bookstore_BookStore_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_bookstore_BookStore_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030book_store_message.proto\022\tbookstore\032\022b" +
      "ook_message.proto\"8\n\tBookStore\022\014\n\004name\030\001" +
      " \001(\t\022\035\n\004book\030\002 \003(\0132\017.bookstore.BookB\036\n\032c" +
      "om.guagua.proto.bookstoreP\000b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.guagua.proto.bookstore.BookMessage.getDescriptor(),
        }, assigner);
    internal_static_bookstore_BookStore_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_bookstore_BookStore_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_bookstore_BookStore_descriptor,
        new java.lang.String[] { "Name", "Book", });
    com.guagua.proto.bookstore.BookMessage.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
