// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_service.proto

package com.guagua.proto.bookstore;

public interface CreateBookResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookstore.CreateBookResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string id = 1;</code>
   */
  java.lang.String getId();
  /**
   * <code>string id = 1;</code>
   */
  com.google.protobuf.ByteString
      getIdBytes();
}
