// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_service.proto

package com.guagua.proto.bookstore;

public interface CreateBookRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:bookstore.CreateBookRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.bookstore.Book book = 1;</code>
   */
  boolean hasBook();
  /**
   * <code>.bookstore.Book book = 1;</code>
   */
  com.guagua.proto.bookstore.Book getBook();
  /**
   * <code>.bookstore.Book book = 1;</code>
   */
  com.guagua.proto.bookstore.BookOrBuilder getBookOrBuilder();
}
