// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: book_service.proto

package com.guagua.proto.bookstore;

/**
 * Protobuf type {@code bookstore.CreateBookResponse}
 */
public  final class CreateBookResponse extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:bookstore.CreateBookResponse)
    CreateBookResponseOrBuilder {
private static final long serialVersionUID = 0L;
  // Use CreateBookResponse.newBuilder() to construct.
  private CreateBookResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private CreateBookResponse() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private CreateBookResponse(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            com.guagua.proto.bookstore.Book.Builder subBuilder = null;
            if (book_ != null) {
              subBuilder = book_.toBuilder();
            }
            book_ = input.readMessage(com.guagua.proto.bookstore.Book.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(book_);
              book_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.guagua.proto.bookstore.BookServiceOuterClass.internal_static_bookstore_CreateBookResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.guagua.proto.bookstore.BookServiceOuterClass.internal_static_bookstore_CreateBookResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.guagua.proto.bookstore.CreateBookResponse.class, com.guagua.proto.bookstore.CreateBookResponse.Builder.class);
  }

  public static final int BOOK_FIELD_NUMBER = 1;
  private com.guagua.proto.bookstore.Book book_;
  /**
   * <code>.bookstore.Book book = 1;</code>
   */
  public boolean hasBook() {
    return book_ != null;
  }
  /**
   * <code>.bookstore.Book book = 1;</code>
   */
  public com.guagua.proto.bookstore.Book getBook() {
    return book_ == null ? com.guagua.proto.bookstore.Book.getDefaultInstance() : book_;
  }
  /**
   * <code>.bookstore.Book book = 1;</code>
   */
  public com.guagua.proto.bookstore.BookOrBuilder getBookOrBuilder() {
    return getBook();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (book_ != null) {
      output.writeMessage(1, getBook());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (book_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getBook());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.guagua.proto.bookstore.CreateBookResponse)) {
      return super.equals(obj);
    }
    com.guagua.proto.bookstore.CreateBookResponse other = (com.guagua.proto.bookstore.CreateBookResponse) obj;

    if (hasBook() != other.hasBook()) return false;
    if (hasBook()) {
      if (!getBook()
          .equals(other.getBook())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasBook()) {
      hash = (37 * hash) + BOOK_FIELD_NUMBER;
      hash = (53 * hash) + getBook().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.guagua.proto.bookstore.CreateBookResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static com.guagua.proto.bookstore.CreateBookResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.guagua.proto.bookstore.CreateBookResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code bookstore.CreateBookResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:bookstore.CreateBookResponse)
      com.guagua.proto.bookstore.CreateBookResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.guagua.proto.bookstore.BookServiceOuterClass.internal_static_bookstore_CreateBookResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.guagua.proto.bookstore.BookServiceOuterClass.internal_static_bookstore_CreateBookResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.guagua.proto.bookstore.CreateBookResponse.class, com.guagua.proto.bookstore.CreateBookResponse.Builder.class);
    }

    // Construct using com.guagua.proto.bookstore.CreateBookResponse.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (bookBuilder_ == null) {
        book_ = null;
      } else {
        book_ = null;
        bookBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.guagua.proto.bookstore.BookServiceOuterClass.internal_static_bookstore_CreateBookResponse_descriptor;
    }

    @java.lang.Override
    public com.guagua.proto.bookstore.CreateBookResponse getDefaultInstanceForType() {
      return com.guagua.proto.bookstore.CreateBookResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.guagua.proto.bookstore.CreateBookResponse build() {
      com.guagua.proto.bookstore.CreateBookResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.guagua.proto.bookstore.CreateBookResponse buildPartial() {
      com.guagua.proto.bookstore.CreateBookResponse result = new com.guagua.proto.bookstore.CreateBookResponse(this);
      if (bookBuilder_ == null) {
        result.book_ = book_;
      } else {
        result.book_ = bookBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.guagua.proto.bookstore.CreateBookResponse) {
        return mergeFrom((com.guagua.proto.bookstore.CreateBookResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.guagua.proto.bookstore.CreateBookResponse other) {
      if (other == com.guagua.proto.bookstore.CreateBookResponse.getDefaultInstance()) return this;
      if (other.hasBook()) {
        mergeBook(other.getBook());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      com.guagua.proto.bookstore.CreateBookResponse parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (com.guagua.proto.bookstore.CreateBookResponse) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private com.guagua.proto.bookstore.Book book_;
    private com.google.protobuf.SingleFieldBuilderV3<
        com.guagua.proto.bookstore.Book, com.guagua.proto.bookstore.Book.Builder, com.guagua.proto.bookstore.BookOrBuilder> bookBuilder_;
    /**
     * <code>.bookstore.Book book = 1;</code>
     */
    public boolean hasBook() {
      return bookBuilder_ != null || book_ != null;
    }
    /**
     * <code>.bookstore.Book book = 1;</code>
     */
    public com.guagua.proto.bookstore.Book getBook() {
      if (bookBuilder_ == null) {
        return book_ == null ? com.guagua.proto.bookstore.Book.getDefaultInstance() : book_;
      } else {
        return bookBuilder_.getMessage();
      }
    }
    /**
     * <code>.bookstore.Book book = 1;</code>
     */
    public Builder setBook(com.guagua.proto.bookstore.Book value) {
      if (bookBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        book_ = value;
        onChanged();
      } else {
        bookBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.bookstore.Book book = 1;</code>
     */
    public Builder setBook(
        com.guagua.proto.bookstore.Book.Builder builderForValue) {
      if (bookBuilder_ == null) {
        book_ = builderForValue.build();
        onChanged();
      } else {
        bookBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.bookstore.Book book = 1;</code>
     */
    public Builder mergeBook(com.guagua.proto.bookstore.Book value) {
      if (bookBuilder_ == null) {
        if (book_ != null) {
          book_ =
            com.guagua.proto.bookstore.Book.newBuilder(book_).mergeFrom(value).buildPartial();
        } else {
          book_ = value;
        }
        onChanged();
      } else {
        bookBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.bookstore.Book book = 1;</code>
     */
    public Builder clearBook() {
      if (bookBuilder_ == null) {
        book_ = null;
        onChanged();
      } else {
        book_ = null;
        bookBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.bookstore.Book book = 1;</code>
     */
    public com.guagua.proto.bookstore.Book.Builder getBookBuilder() {
      
      onChanged();
      return getBookFieldBuilder().getBuilder();
    }
    /**
     * <code>.bookstore.Book book = 1;</code>
     */
    public com.guagua.proto.bookstore.BookOrBuilder getBookOrBuilder() {
      if (bookBuilder_ != null) {
        return bookBuilder_.getMessageOrBuilder();
      } else {
        return book_ == null ?
            com.guagua.proto.bookstore.Book.getDefaultInstance() : book_;
      }
    }
    /**
     * <code>.bookstore.Book book = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        com.guagua.proto.bookstore.Book, com.guagua.proto.bookstore.Book.Builder, com.guagua.proto.bookstore.BookOrBuilder> 
        getBookFieldBuilder() {
      if (bookBuilder_ == null) {
        bookBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            com.guagua.proto.bookstore.Book, com.guagua.proto.bookstore.Book.Builder, com.guagua.proto.bookstore.BookOrBuilder>(
                getBook(),
                getParentForChildren(),
                isClean());
        book_ = null;
      }
      return bookBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:bookstore.CreateBookResponse)
  }

  // @@protoc_insertion_point(class_scope:bookstore.CreateBookResponse)
  private static final com.guagua.proto.bookstore.CreateBookResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.guagua.proto.bookstore.CreateBookResponse();
  }

  public static com.guagua.proto.bookstore.CreateBookResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<CreateBookResponse>
      PARSER = new com.google.protobuf.AbstractParser<CreateBookResponse>() {
    @java.lang.Override
    public CreateBookResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new CreateBookResponse(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<CreateBookResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<CreateBookResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.guagua.proto.bookstore.CreateBookResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

