// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.guagua.proto.hello;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>uint32 id = 1;</code>
   */
  int getId();

  /**
   * <code>string name = 2;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 2;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>uint32 age = 3;</code>
   */
  int getAge();

  /**
   * <pre>
   * 可选字典，
   * optional 在语法3中，不用写默认是 optional
   * </pre>
   *
   * <code>string password = 4;</code>
   */
  java.lang.String getPassword();
  /**
   * <pre>
   * 可选字典，
   * optional 在语法3中，不用写默认是 optional
   * </pre>
   *
   * <code>string password = 4;</code>
   */
  com.google.protobuf.ByteString
      getPasswordBytes();

  /**
   * <code>repeated string address = 5;</code>
   */
  java.util.List<java.lang.String>
      getAddressList();
  /**
   * <code>repeated string address = 5;</code>
   */
  int getAddressCount();
  /**
   * <code>repeated string address = 5;</code>
   */
  java.lang.String getAddress(int index);
  /**
   * <code>repeated string address = 5;</code>
   */
  com.google.protobuf.ByteString
      getAddressBytes(int index);

  /**
   * <code>bool flag = 6;</code>
   */
  boolean getFlag();
}
