// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.guagua.proto.hello;

public interface HelloRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string address_home = 2;</code>
   */
  java.lang.String getAddressHome();
  /**
   * <code>string address_home = 2;</code>
   */
  com.google.protobuf.ByteString
      getAddressHomeBytes();

  /**
   * <pre>
   * 可选字典，
   * </pre>
   *
   * <code>uint32 id = 3;</code>
   */
  int getId();
}
