// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello_service.proto

package com.guagua.proto.hello;

public final class HelloServiceProto {
  private HelloServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023hello_service.proto\022\005hello\032\013hello.prot" +
      "o2@\n\014HelloService\0220\n\003Say\022\023.hello.HelloRe" +
      "quest\032\024.hello.HelloResponseB-\n\026com.guagu" +
      "a.proto.helloB\021HelloServiceProtoP\001b\006prot" +
      "o3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.guagua.proto.hello.Hello.getDescriptor(),
        }, assigner);
    com.guagua.proto.hello.Hello.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
