// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: hello.proto

package com.guagua.proto.hello;

public interface HelloResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:hello.HelloResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string uuid = 1;</code>
   */
  java.lang.String getUuid();
  /**
   * <code>string uuid = 1;</code>
   */
  com.google.protobuf.ByteString
      getUuidBytes();
}
