server:
  port: 8890

spring:
  application:
    name: client

info:
  application:
    name: ${spring.application.name}

management:
  endpoints:
    web:
      exposure:
        include:
          - "*"
  info:
    env:
      enabled: true

dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: false
  registry:
    address: zookeeper://${zookeeper.address:127.0.0.1}:2181
    timeout: 3600000